/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "secondary": "#5f5e60",
        "secondary-fixed": "#e4e2e4",
        "outline-variant": "#d5c4ab",
        "surface-variant": "#e2e2e4",
        "secondary-container": "#e2dfe1",
        "on-secondary-fixed-variant": "#474649",
        "on-surface-variant": "#514532",
        "primary-container": "#ffb800",
        "surface-bright": "#f9f9fb",
        "inverse-surface": "#2f3132",
        "surface-container": "#eeeef0",
        "tertiary-container": "#c5c4c9",
        "outline": "#837560",
        "error-container": "#ffdad6",
        "on-secondary-container": "#636264",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#46464b",
        "on-secondary-fixed": "#1b1b1d",
        "surface-container-low": "#f3f3f5",
        "primary-fixed": "#ffdea8",
        "on-primary-container": "#6b4c00",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e2e2e4",
        "secondary-fixed-dim": "#c8c6c8",
        "tertiary": "#5e5e63",
        "background": "#f9f9fb",
        "on-tertiary-container": "#505156",
        "on-tertiary-fixed": "#1a1b1f",
        "primary-fixed-dim": "#ffba20",
        "on-surface": "#1a1c1d",
        "on-primary-fixed": "#271900",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-primary-fixed-variant": "#5e4200",
        "surface": "#f9f9fb",
        "on-error-container": "#93000a",
        "surface-dim": "#d9dadc",
        "on-secondary": "#ffffff",
        "on-background": "#1a1c1d",
        "surface-tint": "#7c5800",
        "inverse-primary": "#ffba20",
        "on-primary": "#ffffff",
        "primary": "#7c5800",
        "tertiary-fixed": "#e3e2e7",
        "inverse-on-surface": "#f0f0f2",
        "tertiary-fixed-dim": "#c7c6cb",
        "surface-container-high": "#e8e8ea",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
