export const defaultMachines = [
  {
    id: 'm1',
    name: 'Yanmar ViO50',
    desc: 'Náš pracovní kůň pro přesné výkopy v omezených prostorách. Ideální pro základy rodinných domů, pokládání inženýrských sítí a práci v zahradách.',
    image: '/assets/machines/Yanmar.jpeg',
    chip1: 'Pásový minibagr',
    chip2: 'Přesné výkopy',
    spec1_label: 'Hmotnost',
    spec1_value: '4,8 t',
    spec2_label: 'Hloubkový dosah',
    spec2_value: '3,5 m',
  },
  {
    id: 'm2',
    name: 'Takeuchi TB295W',
    desc: 'Kolový bagr pro rychlé přesuny po komunikacích. Kombinuje sílu pásového stroje s mobilitou koleček. Vhodný pro terénní úpravy a výkopy v zástavbě.',
    image: '/assets/machines/Takeuchi.jpeg',
    chip1: 'Kolový bagr',
    chip2: 'Mobilní',
    spec1_label: 'Hmotnost',
    spec1_value: '9,4 t',
    spec2_label: 'Výkon',
    spec2_value: '55 kW',
  },
  {
    id: 'm3',
    name: 'Wacker Neuson EZ36',
    desc: 'Bagr s nulovým zadním přesahem. Pracuje i v těsných prostorách — u plotů, zdí a v interiérech. Ideální pro práce v zahradách a uzavřených dvorech.',
    image: '/assets/machines/Wackerneusonez 36.jpg',
    chip1: 'Pásový minibagr',
    chip2: 'Nulový přesah',
    spec1_label: 'Hmotnost',
    spec1_value: '3,6 t',
    spec2_label: 'Zadní přesah',
    spec2_value: 'Nulový',
  },
  {
    id: 'm4',
    name: 'Tatra 815 Sklápěč 15T',
    desc: 'Robustní sklápěč pro přepravu zeminy, štěrku, písku a suti. Dostaneme se tam, kam jiná auta nedojedou. Operujeme v okruhu 80 km od Netolic.',
    image: '/assets/machines/Tatra.jpeg',
    chip1: 'Nákladní vozidlo',
    chip2: '15 tun',
    spec1_label: 'Nosnost',
    spec1_value: '15 t',
    spec2_label: 'Objem',
    spec2_value: '10 m³',
  },
]

export const defaults = {
  // Hero
  hero_h1_1: 'Architektura terénu',
  hero_h1_2: 's precizností.',

  // Services
  services_label: 'NAŠE SLUŽBY',
  services_h2: 'Co umíme.',
  service_1_name: 'Výkopové práce',
  service_1_desc: 'Přesné hloubení základů, rýh pro inženýrské sítě a terénní úpravy. Pracujeme na rodinných i průmyslových stavbách.',
  service_2_name: 'Doprava materiálu',
  service_2_desc: 'Přeprava zeminy, štěrku, písku a stavebního materiálu sklápěčem Tatra 15T.',
  service_3_name: 'Zakládání staveb',
  service_3_desc: 'Příprava stavebního pozemku, výkopy pro základové pásy a desky.',
  service_4_name: 'Terénní úpravy',
  service_4_desc: 'Modelování terénu, srovnání pozemků, budování svahů a odvodňovacích systémů.',

  // About
  about_label: 'DISCIPLÍNA & ZKUŠENOSTI',
  about_h2: 'Více než 15 let budujeme základy pro vaši budoucnost. Každý pohyb stroje je promyšleným aktem inženýrské přesnosti.',
  about_body: 'Nejsme jen obsluha strojů. Jsme specialisté, kteří chápou fyziku terénu a nároky moderního stavitelství. Naše práce je definována efektivitou, čistotou a absolutním dodržením milimetrových specifikací.',
  stat_1_value: '15+ let',
  stat_1_label: 'Zkušeností',
  stat_2_value: '500+',
  stat_2_label: 'Dokončených projektů',
  stat_3_value: '3 stroje',
  stat_3_label: 'Vždy připraveny',

  // Gallery
  gallery_1_label: 'Výkopové práce – základy RD',
  gallery_1_image: 'https://placehold.co/800x600/1a1c1d/ffb800?text=Výkopové+práce',
  gallery_2_label: 'Inženýrské sítě',
  gallery_2_image: 'https://placehold.co/400x1100/2f3132/ffba20?text=Inženýrské+sítě',
  gallery_3_label: 'Terénní úpravy svahů',
  gallery_3_image: 'https://placehold.co/400x500/514532/ffdea8?text=Terénní+úpravy',
  gallery_4_label: 'Doprava materiálu',
  gallery_4_image: 'https://placehold.co/400x500/1a1c1d/e4e2e4?text=Doprava+materiálu',
  gallery_5_label: 'Zakládání staveb',
  gallery_5_image: 'https://placehold.co/400x500/7c5800/ffffff?text=Základové+desky',

  // Contact
  contact_logo: '/assets/machines/Logo.jpeg',
  contact_phone: '+420 723 753 374',
  contact_email: 'novaja46@seznam.cz',
  contact_address: 'Krtely 6, 384 11 Netolice, Jižní Čechy',
}
